### ISSUE TITLE
Account request

### ISSUE THREAD

**Issue by ghost** [NameIsA/MobileDevice-ProdigyHacking#10]
***What items should be in the account?***: everything in my backpack (hats,wands,boots,items etc. NOTE ABOUT ITEMS make it so the hats and stuff stay bc when a different person make me a hacked account before the stuff in my backpack did not stay) 
        
**the pets that i want are down below** 

i want 2 of each epic but make it so the game will not freeze whenever I go into a battle, 

***What level do you want, how much gold, dark tower floor, etc?***: i want my account to be level 100, 1 million gold, the tree fort house, 13,500 hearts 

***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is dck.dachickenking@gmail.com)***:calebthehufflepuff@gmail.com

**Comment by NameIsA** [comment]
Sorry, I can't keep working on this repository for now. I'm very pre-occupied.

**Comment by NameIsA** [comment]
Feel free to ask @CRobbins0867 if you need an account.
