### ISSUE TITLE
Account request

### ISSUE THREAD

**Issue by savage8685** [NameIsA/MobileDevice-ProdigyHacking#12]
***What items should be in the account?***:

***What level do you want, how much gold, dark tower floor, etc?***:

***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is dck.dachickenking@gmail.com)***:

**Comment by CRobbins0867** [comment]
@savage8685 go here https://github.com/CRobbins0867/ProdigyHacking--MobileHacking/issues/new/ choose put want you want on the account and i will hack it for you also put your email so i can email you the account info

**Comment by savage8685** [comment]
Put what you want on it I will I will make a new acc
