### ISSUE TITLE
Account request

### ISSUE THREAD

**Issue by nate8008** [NameIsA/MobileDevice-ProdigyHacking#13]
***What items should be in the account?***: Mira’s hat and whatever armor Dragons staff, also if you are doing pets, big hex and chill and char.

***What level do you want, how much gold, dark tower floor, etc?***:  all titan armor, lvl 100, 1 mill gold if that’s possible,  

***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is dck.dachickenking@gmail.com)***:
-removed for security-
Tysm u a real one ☝️

**Comment by NameIsA** [comment]
I am not currently maintaining this repository, I apologize.

**Comment by NameIsA** [comment]
Feel free to ask @CRobbins0867 if you need an account.
