### ISSUE TITLE
Account request

### ISSUE THREAD

**Issue by irhrhd** [NameIsA/MobileDevice-ProdigyHacking#15]
***What items should be in the account?***:
Every item and all the buddies including the epics make sure trialmasters is on the account to please
***What level do you want, how much gold, dark tower floor, etc?***:
100 infinite money 100 floor infnite currency please all the pets max level and epics max level please membership to please and Name Be Camden The Wizard thats it
***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is dck.dachickenking@gmail.com)***:
-removed for security-

**Comment by NameIsA** [comment]
At the moment, I am not maintaining this repository, I apologize.

**Comment by irhrhd** [comment]
Mannn i really wanted the account

**Comment by CRobbins0867** [comment]
@irhrhd i will make a account for you if you want, do you want me to???

**Comment by irhrhd** [comment]
Heck yeah just add everything to it including all the buddies the epics too
and all pets max level make it today please also can u make it have
membership to please uh and make sure evry currency and all stones and
level 100 trial matser gear all armor and wands please

**Comment by CRobbins0867** [comment]
got it 
user: funt1425

pass: Finn1

**Comment by CRobbins0867** [comment]
@irhrhd

**Comment by irhrhd** [comment]
Yes

**Comment by CRobbins0867** [comment]
there is the account info up above!

**Comment by irhrhd** [comment]
Thank you wiat does it have membership?

**Comment by CRobbins0867** [comment]
you can't not get membership unless you buy it idk why srry but you have everything else you wanted!!!!!!!!

**Comment by irhrhd** [comment]
Wanna play with me im on airmeld

**Comment by CRobbins0867** [comment]
you mean the server? surre meet me at the ice place

**Comment by CRobbins0867** [comment]
i will be right next to you i will have the wizard nickname too!

**Comment by irhrhd** [comment]
Okay whats your name

**Comment by CRobbins0867** [comment]
bruce the wizard

**Comment by CRobbins0867** [comment]
i see you!

**Comment by irhrhd** [comment]
Where are you

**Comment by CRobbins0867** [comment]
are you camden the wizard

**Comment by irhrhd** [comment]
Yeah i want the ancient relics on my main

**Comment by irhrhd** [comment]
Im camden

**Comment by CRobbins0867** [comment]
okay i saw you go to your house!

**Comment by irhrhd** [comment]
Im there

**Comment by CRobbins0867** [comment]
sorry i gtg!

**Comment by CRobbins0867** [comment]
wait want to be a mod?

**Comment by irhrhd** [comment]
Yeah that would be great im good at moderating

**Comment by CRobbins0867** [comment]
okay i made a server like this one where i hack prodigy accounts so i will ivite you!

**Comment by CRobbins0867** [comment]
done!

**Comment by NameIsA** [comment]
Thank you for the help! @CRobbins0867 

I've edited out the account login details from the message so that other people can't login and change the password.
