### ISSUE TITLE
Can I get acc with a membership and all the pets and all the equipment and the game completed and the tower completed Account request

### ISSUE THREAD

**Issue by whythokid8675** [NameIsA/MobileDevice-ProdigyHacking#16]
***What items should be in the account?***:

***What level do you want, how much gold, dark tower floor, etc?***:

***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is dck.dachickenking@gmail.com)***:

***Would you like to be subscribed to the https://digitalteal.com mailing list? (yes/no)***:
Yes (default)

**Comment by whythokid8675** [comment]
My email is s14936@hindsschools.com

**Comment by NameIsA** [comment]
Please ask CRobbins0867, as I'm not working on this repository at the moment.
