### ISSUE TITLE
Account request Crobbions can I get a acc with all the pets and and the game completed and lvl 1,000 pls and all the other stuff and 590m gold pls

### ISSUE THREAD

**Issue by whythokid8675** [NameIsA/MobileDevice-ProdigyHacking#17]
***What items should be in the account?***:

***What level do you want, how much gold, dark tower floor, etc?***:

***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is dck.dachickenking@gmail.com)***:

***Would you like to be subscribed to the https://digitalteal.com mailing list? (yes/no)***:
Yes (default)

**Comment by whythokid8675** [comment]
My email is s14936@hindsschools.com

**Comment by NameIsA** [comment]
@CRobbins0867

**Comment by whythokid8675** [comment]
Yeah I did thx
