### ISSUE TITLE
Account request

### ISSUE THREAD

**Issue by brads391** [NameIsA/MobileDevice-ProdigyHacking#2]
***What items should be in the account?***: All Items

***What level do you want, how much gold, dark tower floor, etc?***: lvl.100, 99999999999 gold, the last floor in dark tower, all pets and epics.

***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is dck.dachickenking@gmail.com)***: Bradsylvia9@gmail.com

**Comment by NameIsA** [comment]
will work on it asap

**Comment by NameIsA** [comment]
alright sent to your email
