### ISSUE TITLE
i dont wanna put a title but i have to so i will ;-;

### ISSUE THREAD

**Issue by inxtagram** [NameIsA/MobileDevice-ProdigyHacking#3]
***What items should be in the account?***:
Trialmaster's Gear
Mira's Gear
All Epics
And pretty much everything (including furniture)
House-Anything you want really idc smh
***What level do you want, how much gold, dark tower floor, etc?***:
Dark Tower Level-100
Level-100
Gold-100K
***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is dck.dachickenking@gmail.com)***:
shooksy1@gmail.com

**Comment by NameIsA** [comment]
will work on it asap

**Comment by NameIsA** [comment]
copy-pasting this onto all the open issues lol:

mk so my computer wont load prodigy rn lol, im going to work on that, but expect to have to wait a day or so to recieve your account, very srry :>

**Comment by NameIsA** [comment]
Sorry, I can't keep working on this repository for now. I'm very pre-occupied.

**Comment by CRobbins0867** [comment]
@inxtagram if you want me to hack a prodigy account for you click here https://github.com/CRobbins0867/ProdigyHacking--MobileHacking i am hacking prodigy accounts while he is gone so if you want ton go there and fill out a account request issue!

**Comment by NameIsA** [comment]
Thanks @CRobbins0867
