### ISSUE TITLE
Account request

### ISSUE THREAD

**Issue by CRobbins0867** [NameIsA/MobileDevice-ProdigyHacking#4]
***What items should be in the account?***: 2 level 100 epics, 2 level 100 crystal monsters and evdrything in the backpack 

***What level do you want, how much gold, dark tower floor, etc?***: level 100, 99999999999999, gold dark tower level 100, the tree fort house

***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is dck.dachickenking@gmail.com)***: megagjkiller@gmail.com

**Comment by NameIsA** [comment]
will work on it asap

**Comment by NameIsA** [comment]
copy-pasting this onto all the open issues lol:

mk so my computer wont load prodigy rn lol, im going to work on that, but expect to have to wait a day or so to recieve your account, very srry :>

**Comment by NameIsA** [comment]
alright i can get to work on it now!!

**Comment by NameIsA** [comment]
i think its working... respond here or email me if anything's wrong. i've sent you the login details!!! have a great day :3
