### ISSUE TITLE
Account request

### ISSUE THREAD

**Issue by jakewoooooo** [NameIsA/MobileDevice-ProdigyHacking#5]
***What items should be in the account?***:
Trialmaster's Gear
Mira's Gear
All Epics
And pretty much everything (including furniture)
House-Anything
***What level do you want, how much gold, dark tower floor, etc?***:
Level 100 gold 999,999,999 dark tower max floor 999,999,999 titan shards all max currencies membership
***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is dck.dachickenking@gmail.com)***:
jakewil344@gmail.com

**Comment by NameIsA** [comment]
will work on it asap

**Comment by NameIsA** [comment]
copy-pasting this onto all the open issues lol:

mk so my computer wont load prodigy rn lol, im going to work on that, but expect to have to wait a day or so to recieve your account, very srry :>

**Comment by jakewoooooo** [comment]
ok thank you for the trouble

**Comment by NameIsA** [comment]
hi im so sorry i keep procastinating on this- i had to go to school in-person today and now i need to sleep. im going to set a reminder on my phone to do this in the morning

**Comment by jakewoooooo** [comment]
No worries, thanks for the heads up!

**Comment by NameIsA** [comment]
working on it now

**Comment by NameIsA** [comment]
sent

**Comment by jakewoooooo** [comment]
ok thx

**Comment by jakewoooooo** [comment]
where is it

**Comment by NameIsA** [comment]
in your email, i believe?
