### ISSUE TITLE
Account request

### ISSUE THREAD

**Issue by HiWhoIsMe** [NameIsA/MobileDevice-ProdigyHacking#6]
all gear
and all epics
lvl 100, 10000+, 9999999999, 

***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is cz.chelseazhang@gmail.com)***:

**Comment by NameIsA** [comment]
will work on it asap

**Comment by NameIsA** [comment]
sent via email! check your email for the account :>
