### ISSUE TITLE
Account request

### ISSUE THREAD

**Issue by HiWhoIsMe** [NameIsA/MobileDevice-ProdigyHacking#7]
***What items should be in the account?***: all robes, all epics, hacked hairstyles all everything

***What level do you want, how much gold, dark tower floor, etc?***: level 1e+1111111111111 gold: 999999999999999999999  dark tower level: 99999999999999999999

***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is dck.dachickenking@gmail.com)***: cz.chelseazhang@gmail.com (This is for a friend for a bday present)

**Comment by NameIsA** [comment]
Sorry, I can't keep working on this repository for now. I'm very pre-occupied.

**Comment by CRobbins0867** [comment]
@HiWhoIsMe  no, mynameisa is not working on it anymore but i can hack one for you https://github.com/CRobbins0867/ProdigyHacking--MobileHacking/issues/new/choose just click account request and describe what you want on the account!

**Comment by HiWhoIsMe** [comment]
its ok
