### ISSUE TITLE
Can you just give me membership make my account level 99.99999999999 and if you can please change the nickname to flameweilder, give me 1e+999999999 gold and membership you could make my floor tower 666 my email is apersonjust481@gmail.com

### ISSUE THREAD

**Issue by loopy66** [NameIsA/MobileDevice-ProdigyHacking#8]
***What items should be in the account?***:

***What level do you want, how much gold, dark tower floor, etc?***:

***Give me an email that I can use to contact you- this is needed so that I can give you your Prodigy password & username. (my email is dck.dachickenking@gmail.com)***:

**Comment by loopy66** [comment]
As well as all pets items accessories like wands, outfits, boots, hats, currencies, items, make them all 1e+99999999

**Comment by NameIsA** [comment]
Alright.

**Comment by NameIsA** [comment]
i cant do memberships due to how prodigy works, but i can do the rest

**Comment by NameIsA** [comment]
should be sent to your email.. if not, respond here. if so, close this issue. if i dont get a response in like 24 hrs im going to close this issue.

**Comment by loopy66** [comment]
Finished
